🍱asset:
- changed-files:
  - any-glob-to-any-file: ['**/*.avif', '**/*.ico', '**/*.png', '**/*.svg']
♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
⚙️config:
- changed-files:
  - any-glob-to-any-file: '**/*config.*'
dependencies:
- changed-files:
  - any-glob-to-any-file: ['bun.lock', '**/package.json']
docker:
- changed-files:
  - any-glob-to-any-file: ['.dockerignore', 'Dockerfile']
📝documentation:
- changed-files:
  - any-glob-to-any-file: ['@caravan-kidstec/docs/**', '**/*.md']
🚀enhancement:
- all:
  - changed-files:
    - any-glob-to-any-file: '@caravan-kidstec/web/app/**'
    - all-globs-to-all-files: '!@caravan-kidstec/web/app/**/*.test.tsx'
🪸git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '**/.gitignore']
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: ['.devcontainer/*', '.editorconfig', 'biome.json']
✅test:
- changed-files:
  - any-glob-to-any-file: ['@caravan-kidstec/web/happydom.tsx', '@caravan-kidstec/web/test/**']
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
