[global]
respect-gitignore = true
include = ["**/*.md", "**/*.mdx"]
exclude = [
  "@caravan-kidstec/docs/**",
  "@caravan-kidstec/web/README.md",
  ".github/pull_request_template.md",
  "CODE_OF_CONDUCT.md",
  "CONTRIBUTING.md",
  "README.md",
]

[MD013]
line-length = 120
