name: 📝 Documentation Report
description: Report an issue with the documentation
title: "📝Docs[scope]: "
type: Documentation
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation report🤗

        If you need help or support, and are not reporting a issue, please join our
        [Discord](https://discord.gg/tSHMqK8VDU) server, where you can ask questions in the [`#help`](https://discord.gg/bYA8kWPEg4) forum.

        Make sure you are reading the latest version.
        The issue you are experiencing may already have been fixed.

        Please try to include as much information as possible.
  - type: dropdown
    attributes:
      label: What is the type of issue?
      multiple: true
      options:
        - Documentation is missing
        - Documentation is incorrect
        - Documentation is confusing
        - Example code is not working
        - Something else
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: "Example: https://openup-labtakizawa.github.io/caravan-kidstec/docs/tutorial/intro"
  - type: checkboxes
    id: terms
    attributes:
      label: ⚖️ Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OpenUp-LabTakizawa/caravan-kidstec/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
