name: Auto Assign

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  assign:
    runs-on: ubuntu-24.04

    steps:
      - name: Choose an Assignee
        id: assignee
        env:
          PULL_REQUEST_ASSIGNEE: ${{ toJson(github.event.pull_request.assignees) }}
        run: |
          echo "$PULL_REQUEST_ASSIGNEE"
          echo ASSIGNEE=$(shuf -e HaradaTakayuki kazutan1230 Marukome0743 tanePON -n 1) >> $GITHUB_OUTPUT

      - name: Assign Issue
        if: github.event_name == 'issues' && toJSON(github.event.issue.assignees) == '[]'
        env:
          ASSIGNEE: ${{ steps.assignee.outputs.ASSIGNEE }}
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee $ASSIGNEE --repo ${{ github.repository }}

      - name: Assign Pull Request
        if: github.event_name == 'pull_request' && !github.event.pull_request.assignees
        env:
          ASSIGNEE: ${{ steps.assignee.outputs.ASSIGNEE }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee $ASSIGNEE --repo ${{ github.repository }}
