name: 📝 Check Conventional Commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🐣 Install bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
        with:
          bun-version: canary
      - name: 📦 Install commitlint
        run: bun add -d @commitlint/cli @commitlint/config-conventional
      - name: 📝 Create commitlint config
        run: |
          echo 'export default { extends: ["@commitlint/config-conventional"],
          ignores: [(message) => message.includes("Signed-off-by: dependabot[bot]")] }' > commitlint.config.ts

      - name: 👀 Validate current commit (last commit) with commitlint
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: bunx commitlint --last --verbose

      - name: 👀 Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
