name: 📝 Check Conventional Commit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    outputs:
      is_success: ${{ steps.commitlint.outputs.is_success }}
      commitlint_log: ${{ steps.commitlint.outputs.commitlint_log }}
    if: startsWith(github.ref_name, 'sapling-pr-archive-') == false

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 🐣 Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary
      - uses: ./.github/actions/setup-commitlint

      - name: 👀 Validate current commit (last commit) with commitlint
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: bun commitlint --last --verbose

      - name: 👀 Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        id: commitlint
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          bun commitlint --from $BASE_SHA --to $HEAD_SHA --verbose \
          &> >(tee -p commitlint.log) || STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo "is_success=false" >> $GITHUB_OUTPUT
          else
            echo "is_success=true" >> $GITHUB_OUTPUT
          fi
          UUID=$(uuidgen)
          {
            echo "commitlint_log<<EOF_$UUID"
            cat commitlint.log
            echo "EOF_$UUID"
          } >> $GITHUB_OUTPUT

      - name: 💔 Fail if test failed
        if: steps.commitlint.outputs.is_success == 'false'
        run: exit 1

  upload:
    runs-on: ubuntu-latest
    needs: commitlint
    if: (success() || failure()) && github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/upload-pr-comment
        with:
          is_success: ${{ needs.commitlint.outputs.is_success }}
          success_title: >-
            Commitlint Passed
          success_body: |
            Thank you for updating the commit message to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
          failure_title: >-
            Commitlint Failed
          failure_body: |
            @${{ github.actor }}, your commit ${{ github.event.pull_request.head.sha }} failed the commitlint check.


            <details>

            <summary><strong>Commitlint Log</strong></summary>


            ```shell

            ${{ needs.commitlint.outputs.commitlint_log }}

            ```


            </details>


            Please update the commit message to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

            👀[View in Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          workflow_file: commitlint.yml
