name: ✨ Check Conventional Commit Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: read

jobs:
  lint-title:
    runs-on: ubuntu-latest
    outputs:
      is_success: ${{ steps.commitlint.outputs.is_success }}
      commitlint_log: ${{ steps.commitlint.outputs.commitlint_log }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 🐣 Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary
      - uses: ./.github/actions/setup-commitlint

      - name: 👀 Validate PR title with commitlint
        id: commitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$TITLE" | bun commitlint --verbose &> >(tee -p commitlint.log) || STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo "is_success=false" >> $GITHUB_OUTPUT
          else
            echo "is_success=true" >> $GITHUB_OUTPUT
          fi
          UUID=$(uuidgen)
          {
            echo "commitlint_log<<EOF_$UUID"
            cat commitlint.log
            echo "EOF_$UUID"
          } >> $GITHUB_OUTPUT

      - name: 💔 Fail if test failed
        if: steps.commitlint.outputs.is_success == 'false'
        run: exit 1

  upload:
    runs-on: ubuntu-latest
    needs: lint-title
    if: success() || failure()

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ./.github/actions/upload-pr-comment
        with:
          is_success: ${{ needs.lint-title.outputs.is_success }}
          success_title: >-
            Pull Request Title Linting Passed
          success_body: |
            Thank you for updating the title of this pull request to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
          failure_title: >-
            Pull Request Title Linting Failed
          failure_body: |
            @${{ github.actor }}, thank you for opening this pull request 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.


            <details>

            <summary><strong>Commitlint Log</strong></summary>


            ```shell

            ${{ needs.lint-title.outputs.commitlint_log }}

            ```


            </details>


            Please update the title of this pull request to follow the specification.

            👀[View in Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          workflow_file: pull-request-title-lint.yml
