name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

env:
  VERSION: ${{ github.event.inputs.version || github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openup-labtakizawa'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if the release has already been created
        run: echo RELEASE_EXISTS=$(gh release list | grep "$VERSION") >> $GITHUB_ENV

      - name: Create release
        if: env.RELEASE_EXISTS == ''
        run: gh release create "$VERSION" --generate-notes -t "$REPO_NAME $VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: ${{ github.event.repository.name }}
